import { IDesign } from "./DesignEditor"

const templateDesigns: IDesign[] = [
  {
    id: "SM60PQxCHNwhet_RlqbJD",
    type: "GRAPHIC",
    name: "Untitled Design",
    frame: { width: 1200, height: 1200 },
    scenes: [
      {
        id: "g2bBAN2en9ig97ypnSmfh",
        layers: [
          {
            id: "background",
            name: "Initial Frame",
            angle: 0,
            stroke: null,
            strokeWidth: 0,
            left: 0,
            top: 0,
            width: 1200,
            height: 1200,
            opacity: 1,
            originX: "left",
            originY: "top",
            scaleX: 1,
            scaleY: 1,
            type: "Background",
            flipX: false,
            flipY: false,
            skewX: 0,
            skewY: 0,
            visible: true,
            shadow: { color: "#fcfcfc", blur: 4, offsetX: 0, offsetY: 0, affectStroke: false, nonScaling: false },
            fill: "#ffffff",
            metadata: {},
          },
          {
            id: "PqNgFTbQNQpE8TctAsMdb",
            name: "StaticImage",
            angle: 0,
            stroke: null,
            strokeWidth: 0,
            left: 275,
            top: 261,
            width: 650,
            height: 650,
            opacity: 1,
            originX: "left",
            originY: "top",
            scaleX: 1,
            scaleY: 1,
            type: "StaticImage",
            flipX: false,
            flipY: false,
            skewX: 0,
            skewY: 0,
            visible: true,
            shadow: null,
            src: "https://images.pexels.com/photos/789555/pexels-photo-789555.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
            cropX: 0,
            cropY: 0,
            metadata: {},
          },
          {
            id: "Mt90tOtObkH_Iubs0BoP7",
            name: "StaticImage",
            angle: 0,
            stroke: null,
            strokeWidth: 0,
            left: -73.33,
            top: 481.1,
            width: 650,
            height: 650,
            opacity: 1,
            originX: "left",
            originY: "top",
            scaleX: 1,
            scaleY: 1,
            type: "StaticImage",
            flipX: false,
            flipY: false,
            skewX: 0,
            skewY: 0,
            visible: true,
            shadow: null,
            src: "https://images.pexels.com/photos/670741/pexels-photo-670741.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
            cropX: 0,
            cropY: 0,
            metadata: {},
          },
        ],
        name: "Untitled design",
      },
    ],
    metadata: {},
    previews: [
      {id : '', src: 'https://images.pexels.com/photos/789555/pexels-photo-789555.jpeg?auto=compress&cs=tinysrgb&h=650&w=940'},
    ],
    published: false,
  },
]

export default templateDesigns
